version: '3.2'

services:
  g4f_php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: g4f_php
    tty: true
    volumes:
      - ./:/g4f
    restart: unless-stopped
    links:
      - 'db:db'
    networks:
      - g4f
    ports:
      - '9002:9002'
  db:
    image: 'mysql:latest'
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: g4f_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    restart: unless-stopped
    networks:
      - g4f
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

networks:
  g4f:
    driver: bridge